import { DEFAULT_STYLE, type SubtitleStyle } from "@/lib/subtitles/style";

// Caplio Styles 2.0 — curated catalog (Hypro-like viral looks + Caplio-unique Negative/Ember).
// Landing demos and the editor StylePanel both consume this list.

export type PresetCategory =
  | "aesthetic"
  | "impact"
  | "sync"
  | "cinematic"
  | "build"
  | "quiet"
  | "premium";

export interface StylePreset {
  id: string;
  name: string;
  category: PresetCategory;
  /** Short chip shown on the card (Aesthetic, Karaoke, …). */
  tag?: string;
  /** Short sample shown on the picker card. */
  sample?: string;
  /**
   * Landing CSS animation key (maps to `.lp-anim-*`). Optional — editor cards
   * ignore this and render from `style`.
   */
  landingAnim?: string;
  /** Styles generation — 2.0 curated viral set, 3.0 premium atelier looks. */
  generation?: "2.0" | "3.0";
  /** Default words-per-frame when this preset is applied (Styles 3.0). */
  wordsPerFrame?: number;
  style: SubtitleStyle;
}

export const PRESET_CATEGORIES: { id: PresetCategory | "all"; label: string }[] = [
  { id: "all", label: "All" },
  { id: "aesthetic", label: "Aesthetic" },
  { id: "impact", label: "Impact" },
  { id: "sync", label: "Sync" },
  { id: "cinematic", label: "Cinematic" },
  { id: "build", label: "Build" },
  { id: "quiet", label: "Quiet" },
  { id: "premium", label: "Premium" },
];

const ACCENT_RED = "#FF3B30";
const ACCENT_NEON = "#FF4EC8";
const ATELIER_BLUE = "#2E90FF";

/** Styles 2.0 — 14 curated presets. */
export const PRESETS: StylePreset[] = [
  {
    id: "classic",
    name: "Classic",
    category: "aesthetic",
    tag: "Default",
    sample: "GUARANTEES",
    landingAnim: "classic",
    style: { ...DEFAULT_STYLE },
  },
  {
    id: "bold",
    name: "Bold",
    category: "impact",
    tag: "Impact",
    sample: "WATCH THIS",
    landingAnim: "bold",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "Anton",
      fontWeight: 400,
      fontSizePct: 6.5,
      color: "#FFFFFF",
      outlineColor: "#000000",
      outlineWidth: 4,
      shadow: true,
      glowStrength: 0,
      backgroundOpacity: 0,
      boxMode: "none",
      positionYPct: 78,
      maxWidthPct: 90,
      letterSpacingEm: 0.02,
      lineHeight: 1,
      textCase: "upper",
      uppercase: true,
      karaoke: false,
      emphasisMode: "off",
      animation: "pop",
      textEffect: "none",
      highlightColor: "#FFFFFF",
    },
  },
  {
    id: "minimal",
    name: "Minimal",
    category: "quiet",
    tag: "Quiet",
    sample: "quietly",
    landingAnim: "minimal",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "Inter",
      fontWeight: 500,
      fontSizePct: 3.2,
      color: "#FFFFFF",
      outlineWidth: 0,
      shadow: true,
      glowStrength: 0,
      backgroundOpacity: 0,
      boxMode: "none",
      positionYPct: 86,
      maxWidthPct: 78,
      letterSpacingEm: 0.18,
      lineHeight: 1.2,
      textCase: "upper",
      uppercase: true,
      karaoke: false,
      emphasisMode: "off",
      animation: "fade",
      textEffect: "none",
      highlightColor: "#FFFFFF",
    },
  },
  {
    id: "highlight",
    name: "Highlight",
    category: "aesthetic",
    tag: "Aesthetic",
    sample: "this",
    landingAnim: "highlight",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "Inter",
      fontWeight: 700,
      fontSizePct: 3.6,
      color: "#111111",
      highlightColor: "#111111",
      outlineWidth: 0,
      shadow: false,
      glowStrength: 0,
      backgroundColor: "#FFE600",
      backgroundOpacity: 1,
      bgPaddingXPct: 1.8,
      bgPaddingYPct: 0.7,
      boxMode: "inline",
      boxRadiusPct: 0.15,
      positionYPct: 54,
      maxWidthPct: 86,
      letterSpacingEm: -0.01,
      lineHeight: 1.1,
      textCase: "lower",
      uppercase: false,
      karaoke: false,
      emphasisMode: "off",
      animation: "fade",
      textEffect: "none",
    },
  },
  {
    id: "punch",
    name: "Punch",
    category: "impact",
    tag: "One word",
    sample: "THIS",
    landingAnim: "punch",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "Anton",
      fontWeight: 400,
      fontSizePct: 7.5,
      color: ACCENT_RED,
      highlightColor: ACCENT_RED,
      outlineWidth: 0,
      shadow: true,
      glowStrength: 0,
      backgroundOpacity: 0,
      boxMode: "none",
      positionYPct: 50,
      maxWidthPct: 92,
      letterSpacingEm: -0.03,
      lineHeight: 1,
      textCase: "upper",
      uppercase: true,
      karaoke: false,
      emphasisMode: "off",
      animation: "flash",
      textEffect: "none",
    },
  },
  {
    id: "glow",
    name: "Glow",
    category: "aesthetic",
    tag: "Aesthetic",
    sample: "ownership",
    landingAnim: "glow",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "Montserrat",
      fontWeight: 700,
      fontSizePct: 4.8,
      color: "#FFFFFF",
      highlightColor: ACCENT_NEON,
      outlineWidth: 0,
      shadow: false,
      glowStrength: 5,
      glowColor: ACCENT_NEON,
      backgroundOpacity: 0,
      boxMode: "none",
      positionYPct: 52,
      maxWidthPct: 90,
      letterSpacingEm: -0.01,
      lineHeight: 1.05,
      textCase: "sentence",
      uppercase: false,
      karaoke: false,
      emphasisMode: "off",
      animation: "hook",
      textEffect: "none",
    },
  },
  {
    id: "outline",
    name: "Outline",
    category: "impact",
    tag: "Editorial",
    sample: "YOU",
    landingAnim: "outline",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "Anton",
      fontWeight: 400,
      fontSizePct: 7.0,
      color: "#FFFFFF",
      outlineColor: "#FFFFFF",
      outlineWidth: 2.5,
      shadow: false,
      glowStrength: 0,
      backgroundOpacity: 0,
      boxMode: "none",
      positionYPct: 50,
      maxWidthPct: 88,
      letterSpacingEm: 0.04,
      lineHeight: 1,
      textCase: "upper",
      uppercase: true,
      karaoke: false,
      emphasisMode: "off",
      animation: "pop",
      textEffect: "none",
      highlightColor: "#FFFFFF",
    },
  },
  {
    id: "typewriter",
    name: "Typewriter",
    category: "build",
    tag: "Build",
    sample: "this is how",
    landingAnim: "type",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "Montserrat",
      fontWeight: 700,
      fontSizePct: 4.4,
      color: "#FFFFFF",
      highlightColor: "#FFFFFF",
      outlineWidth: 0,
      shadow: true,
      glowStrength: 0,
      backgroundOpacity: 0,
      boxMode: "none",
      positionYPct: 54,
      maxWidthPct: 88,
      letterSpacingEm: -0.02,
      lineHeight: 1.15,
      textCase: "lower",
      uppercase: false,
      karaoke: false,
      emphasisMode: "off",
      animation: "typewriter",
      textEffect: "none",
    },
  },
  {
    id: "cinema",
    name: "Cinema",
    category: "cinematic",
    tag: "Cinematic",
    sample: "this is",
    landingAnim: "cinema",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "Instrument Serif",
      fontWeight: 400,
      fontSizePct: 4.2,
      color: "#FFFFFF",
      highlightColor: "#FFFFFF",
      outlineWidth: 0,
      shadow: true,
      glowStrength: 0,
      backgroundOpacity: 0,
      boxMode: "none",
      positionYPct: 46,
      maxWidthPct: 80,
      letterSpacingEm: 0.01,
      lineHeight: 1.2,
      textCase: "lower",
      uppercase: false,
      karaoke: false,
      emphasisMode: "off",
      animation: "fade",
      textEffect: "none",
    },
  },
  {
    id: "karaoke",
    name: "Karaoke",
    category: "sync",
    tag: "Sync",
    sample: "viral",
    landingAnim: "karaoke",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "Montserrat",
      fontWeight: 700,
      fontSizePct: 4.6,
      color: "#FFFFFF",
      highlightColor: ACCENT_RED,
      outlineWidth: 0,
      shadow: true,
      glowStrength: 0,
      backgroundOpacity: 0,
      boxMode: "none",
      positionYPct: 56,
      maxWidthPct: 90,
      letterSpacingEm: -0.02,
      lineHeight: 1.15,
      textCase: "lower",
      uppercase: false,
      karaoke: true,
      emphasisMode: "off",
      animation: "fade",
      textEffect: "none",
    },
  },
  {
    id: "soft-focus",
    name: "Soft Focus",
    category: "quiet",
    tag: "Soft focus",
    sample: "this is",
    landingAnim: "blur",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "Inter",
      fontWeight: 400,
      fontSizePct: 2.8,
      color: "#FFFFFF",
      highlightColor: "#FFFFFF",
      outlineWidth: 0,
      shadow: true,
      glowStrength: 0,
      backgroundOpacity: 0,
      boxMode: "none",
      positionYPct: 28,
      maxWidthPct: 70,
      letterSpacingEm: 0.02,
      lineHeight: 1.2,
      textCase: "lower",
      uppercase: false,
      karaoke: false,
      emphasisMode: "off",
      animation: "fade",
      textEffect: "none",
    },
  },
  {
    id: "motion",
    name: "Motion",
    category: "cinematic",
    tag: "Cinematic",
    sample: "this is",
    landingAnim: "motion",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "Montserrat",
      fontWeight: 700,
      fontSizePct: 5.2,
      color: "#FFFFFF",
      highlightColor: "#FFFFFF",
      outlineWidth: 0,
      shadow: true,
      glowStrength: 0,
      backgroundOpacity: 0,
      boxMode: "none",
      positionYPct: 48,
      maxWidthPct: 92,
      letterSpacingEm: -0.02,
      lineHeight: 1,
      textCase: "lower",
      uppercase: false,
      karaoke: false,
      emphasisMode: "off",
      animation: "kinetic",
      textEffect: "none",
    },
  },
  {
    id: "negative",
    name: "Negative",
    category: "aesthetic",
    tag: "Aesthetic",
    sample: "THIS",
    landingAnim: "bold",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "Anton",
      fontWeight: 400,
      fontSizePct: 7.2,
      color: "#FFFFFF",
      highlightColor: "#FFFFFF",
      outlineWidth: 0,
      shadow: false,
      glowStrength: 0,
      backgroundOpacity: 0,
      boxMode: "none",
      positionYPct: 48,
      maxWidthPct: 90,
      letterSpacingEm: -0.02,
      lineHeight: 1,
      textCase: "upper",
      uppercase: true,
      karaoke: false,
      emphasisMode: "off",
      animation: "pop",
      textEffect: "negative",
    },
  },
  {
    id: "ember",
    name: "Ember",
    category: "aesthetic",
    tag: "Aesthetic",
    sample: "VIRAL",
    landingAnim: "glow",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "Anton",
      fontWeight: 400,
      fontSizePct: 7.8,
      color: "#FF6A00",
      highlightColor: "#FF2D2D",
      outlineWidth: 0,
      shadow: false,
      glowStrength: 3,
      glowColor: "#FF3B30",
      backgroundOpacity: 0,
      boxMode: "none",
      positionYPct: 48,
      maxWidthPct: 92,
      letterSpacingEm: -0.02,
      lineHeight: 1,
      textCase: "upper",
      uppercase: true,
      karaoke: false,
      emphasisMode: "off",
      animation: "pop",
      textEffect: "ember",
    },
  },
];

/** Styles 3.0 — premium atelier looks (Klickpin-inspired elegant kinetic). */
export const PRESETS_V3: StylePreset[] = [
  {
    id: "atelier",
    name: "Atelier",
    category: "premium",
    tag: "Premium 3.0",
    sample: "anywhere",
    generation: "3.0",
    wordsPerFrame: 3,
    landingAnim: "cinema",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "Montserrat",
      fontWeight: 700,
      fontSizePct: 4.6,
      color: "#FFFFFF",
      highlightColor: ATELIER_BLUE,
      outlineWidth: 0,
      shadow: true,
      glowStrength: 0,
      backgroundOpacity: 0,
      boxMode: "none",
      positionYPct: 52,
      maxWidthPct: 88,
      letterSpacingEm: -0.03,
      lineHeight: 1,
      textCase: "lower",
      uppercase: false,
      karaoke: false,
      emphasisMode: "off",
      animation: "atelier",
      textEffect: "none",
    },
  },
  {
    id: "telugu-connects",
    name: "Telugu Connects",
    category: "premium",
    tag: "Premium 3.0",
    sample: "Butterflies",
    generation: "3.0",
    wordsPerFrame: 2,
    landingAnim: "cinema",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "Montserrat",
      fontWeight: 700,
      fontSizePct: 5.2,
      color: "#FFFFFF",
      highlightColor: "#FFFFFF",
      outlineWidth: 0,
      shadow: true,
      glowStrength: 0,
      backgroundOpacity: 0,
      boxMode: "none",
      positionYPct: 52,
      maxWidthPct: 88,
      letterSpacingEm: -0.04,
      lineHeight: 0.95,
      textCase: "none",
      uppercase: false,
      karaoke: false,
      emphasisMode: "off",
      animation: "romance",
      textEffect: "none",
    },
  },
];

/** Full catalog — Styles 2.0 + Styles 3.0. */
export const ALL_PRESETS: StylePreset[] = [...PRESETS, ...PRESETS_V3];

/** Find the preset whose style matches `style` field-for-field (used to highlight the card). */
export function matchingPresetId(style: SubtitleStyle): string | null {
  for (const p of ALL_PRESETS) {
    if (stylesEqual(p.style, style)) return p.id;
  }
  return null;
}

export function getPresetById(id: string): StylePreset | undefined {
  return ALL_PRESETS.find((p) => p.id === id);
}

function stylesEqual(a: SubtitleStyle, b: SubtitleStyle): boolean {
  const keys = Object.keys(DEFAULT_STYLE) as (keyof SubtitleStyle)[];
  return keys.every((k) => a[k] === b[k]);
}
