import { DEFAULT_STYLE, type SubtitleStyle } from "@/lib/subtitles/style";

// Named starting points that show off the bundled fonts and common subtitle looks.
// Each is a full SubtitleStyle so selecting one resets every control predictably.

export type PresetCategory =
  | "live"
  | "social"
  | "cinematic"
  | "karaoke"
  | "minimal";

export interface StylePreset {
  id: string;
  name: string;
  category: PresetCategory;
  /** Clipvo-style tag shown on the card (Aesthetic, Karaoke, …). */
  tag?: string;
  /** Short sample shown on the picker card. */
  sample?: string;
  style: SubtitleStyle;
}

export const PRESET_CATEGORIES: { id: PresetCategory | "all"; label: string }[] = [
  { id: "all", label: "All" },
  { id: "live", label: "Live" },
  { id: "social", label: "Social" },
  { id: "cinematic", label: "Cinematic" },
  { id: "karaoke", label: "Karaoke" },
  { id: "minimal", label: "Minimal" },
];

/** Clipvo accent used across Punchline / Karaoke / Headline / Ember. */
const LIVE_ACCENT = "#FF3B30";

export const PRESETS: StylePreset[] = [
  // —— Live (Clipvo-inspired “Forty ways to say it”) ——
  {
    id: "live-negative",
    name: "Negative",
    category: "live",
    tag: "Aesthetic",
    sample: "THIS",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "Anton",
      fontWeight: 400,
      fontSizePct: 7.2,
      color: "#FFFFFF",
      highlightColor: "#FFFFFF",
      outlineWidth: 0,
      shadow: false,
      glowStrength: 0,
      backgroundOpacity: 0,
      boxMode: "none",
      align: "center",
      positionYPct: 48,
      maxWidthPct: 90,
      letterSpacingEm: -0.02,
      lineHeight: 1,
      textCase: "upper",
      uppercase: true,
      karaoke: false,
      emphasisMode: "off",
      animation: "pop",
      textEffect: "negative",
    },
  },
  {
    id: "live-boxed",
    name: "Boxed",
    category: "live",
    tag: "Boxed",
    sample: "THIS",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "Montserrat",
      fontWeight: 700,
      fontSizePct: 4.2,
      color: "#FFFFFF",
      highlightColor: "#FFFFFF",
      outlineWidth: 0,
      shadow: false,
      glowStrength: 0,
      backgroundColor: LIVE_ACCENT,
      backgroundOpacity: 1,
      bgPaddingXPct: 2.4,
      bgPaddingYPct: 1.1,
      boxMode: "inline",
      boxRadiusPct: 0.2,
      align: "center",
      positionYPct: 52,
      maxWidthPct: 88,
      letterSpacingEm: 0.04,
      lineHeight: 1,
      textCase: "upper",
      uppercase: true,
      karaoke: false,
      emphasisMode: "off",
      animation: "pop",
      textEffect: "none",
    },
  },
  {
    id: "live-punchline",
    name: "Punchline",
    category: "live",
    tag: "One word",
    sample: "THIS",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "Anton",
      fontWeight: 400,
      fontSizePct: 7.5,
      color: LIVE_ACCENT,
      highlightColor: LIVE_ACCENT,
      outlineWidth: 0,
      shadow: true,
      glowStrength: 0,
      backgroundOpacity: 0,
      boxMode: "none",
      align: "center",
      positionYPct: 50,
      maxWidthPct: 92,
      letterSpacingEm: -0.03,
      lineHeight: 1,
      textCase: "upper",
      uppercase: true,
      karaoke: false,
      emphasisMode: "off",
      animation: "flash",
      textEffect: "none",
    },
  },
  {
    id: "live-highlighter",
    name: "Highlighter",
    category: "live",
    tag: "Aesthetic",
    sample: "this",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "Inter",
      fontWeight: 700,
      fontSizePct: 3.6,
      color: "#111111",
      highlightColor: "#111111",
      outlineWidth: 0,
      shadow: false,
      glowStrength: 0,
      backgroundColor: "#FFE600",
      backgroundOpacity: 1,
      bgPaddingXPct: 1.8,
      bgPaddingYPct: 0.7,
      boxMode: "inline",
      boxRadiusPct: 0.15,
      align: "center",
      positionYPct: 54,
      maxWidthPct: 86,
      letterSpacingEm: -0.01,
      lineHeight: 1.1,
      textCase: "lower",
      uppercase: false,
      karaoke: false,
      emphasisMode: "off",
      animation: "fade",
      textEffect: "none",
    },
  },
  {
    id: "live-karaoke",
    name: "Karaoke",
    category: "live",
    tag: "Karaoke",
    sample: "viral",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "Montserrat",
      fontWeight: 700,
      fontSizePct: 4.6,
      color: "#FFFFFF",
      highlightColor: LIVE_ACCENT,
      outlineWidth: 0,
      shadow: true,
      glowStrength: 0,
      backgroundOpacity: 0,
      boxMode: "none",
      align: "center",
      positionYPct: 56,
      maxWidthPct: 90,
      letterSpacingEm: -0.02,
      lineHeight: 1.15,
      textCase: "lower",
      uppercase: false,
      karaoke: true,
      emphasisMode: "off",
      animation: "fade",
      textEffect: "none",
    },
  },
  {
    id: "live-headline",
    name: "Headline",
    category: "live",
    tag: "Editorial",
    sample: "viral",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "Instrument Serif",
      fontWeight: 400,
      fontSizePct: 5.4,
      color: "#FFFFFF",
      highlightColor: LIVE_ACCENT,
      outlineWidth: 0,
      shadow: true,
      glowStrength: 0,
      backgroundOpacity: 0,
      boxMode: "none",
      align: "center",
      positionYPct: 50,
      maxWidthPct: 88,
      letterSpacingEm: -0.01,
      lineHeight: 1.05,
      textCase: "lower",
      uppercase: false,
      karaoke: false,
      emphasisMode: "off",
      animation: "editorial",
      textEffect: "none",
    },
  },
  {
    id: "live-typewriter",
    name: "Typewriter",
    category: "live",
    tag: "Build",
    sample: "this is how",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "Montserrat",
      fontWeight: 700,
      fontSizePct: 4.4,
      color: "#FFFFFF",
      highlightColor: "#FFFFFF",
      outlineWidth: 0,
      shadow: true,
      glowStrength: 0,
      backgroundOpacity: 0,
      boxMode: "none",
      align: "center",
      positionYPct: 54,
      maxWidthPct: 88,
      letterSpacingEm: -0.02,
      lineHeight: 1.15,
      textCase: "lower",
      uppercase: false,
      karaoke: false,
      emphasisMode: "off",
      animation: "typewriter",
      textEffect: "none",
    },
  },
  {
    id: "live-ember",
    name: "Ember",
    category: "live",
    tag: "Aesthetic",
    sample: "VIRAL",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "Anton",
      fontWeight: 400,
      fontSizePct: 7.8,
      color: "#FF6A00",
      highlightColor: "#FF2D2D",
      outlineWidth: 0,
      shadow: false,
      glowStrength: 3,
      glowColor: "#FF3B30",
      backgroundOpacity: 0,
      boxMode: "none",
      align: "center",
      positionYPct: 48,
      maxWidthPct: 92,
      letterSpacingEm: -0.02,
      lineHeight: 1,
      textCase: "upper",
      uppercase: true,
      karaoke: false,
      emphasisMode: "off",
      animation: "pop",
      textEffect: "ember",
    },
  },
  {
    id: "live-soft-focus",
    name: "Soft Focus",
    category: "live",
    tag: "Cinematic",
    sample: "this is",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "Inter",
      fontWeight: 400,
      fontSizePct: 2.8,
      color: "#FFFFFF",
      highlightColor: "#FFFFFF",
      outlineWidth: 0,
      shadow: true,
      glowStrength: 0,
      backgroundOpacity: 0,
      boxMode: "none",
      align: "center",
      positionYPct: 28,
      maxWidthPct: 70,
      letterSpacingEm: 0.02,
      lineHeight: 1.2,
      textCase: "lower",
      uppercase: false,
      karaoke: false,
      emphasisMode: "off",
      animation: "fade",
      textEffect: "none",
    },
  },
  {
    id: "live-cinematic-cut",
    name: "Cinematic Cut",
    category: "live",
    tag: "Cinematic",
    sample: "this is",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "Montserrat",
      fontWeight: 700,
      fontSizePct: 4.0,
      color: "#FFFFFF",
      highlightColor: "#FFFFFF",
      outlineWidth: 0,
      shadow: true,
      glowStrength: 0,
      backgroundOpacity: 0,
      boxMode: "none",
      align: "center",
      positionYPct: 48,
      maxWidthPct: 78,
      letterSpacingEm: -0.01,
      lineHeight: 1.15,
      textCase: "lower",
      uppercase: false,
      karaoke: false,
      emphasisMode: "off",
      animation: "fade",
      textEffect: "none",
    },
  },
  {
    id: "live-cinetop",
    name: "Cinetop",
    category: "live",
    tag: "Cinematic",
    sample: "this is",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "Instrument Serif",
      fontWeight: 400,
      fontSizePct: 4.2,
      color: "#FFFFFF",
      highlightColor: "#FFFFFF",
      outlineWidth: 0,
      shadow: true,
      glowStrength: 0,
      backgroundOpacity: 0,
      boxMode: "none",
      align: "center",
      positionYPct: 46,
      maxWidthPct: 80,
      letterSpacingEm: 0.01,
      lineHeight: 1.2,
      textCase: "lower",
      uppercase: false,
      karaoke: false,
      emphasisMode: "off",
      animation: "fade",
      textEffect: "none",
    },
  },
  {
    id: "live-motion",
    name: "Motion",
    category: "live",
    tag: "Cinematic",
    sample: "this is",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "Anton",
      fontWeight: 400,
      fontSizePct: 5.8,
      color: "#FFFFFF",
      highlightColor: "#FFFFFF",
      outlineWidth: 0,
      shadow: true,
      glowStrength: 0,
      backgroundOpacity: 0,
      boxMode: "none",
      align: "center",
      positionYPct: 50,
      maxWidthPct: 86,
      letterSpacingEm: -0.03,
      lineHeight: 1,
      textCase: "lower",
      uppercase: false,
      karaoke: false,
      emphasisMode: "off",
      animation: "pop",
      textEffect: "none",
    },
  },

  // —— Social ——
  {
    id: "tharun-speaks",
    name: "Tharun Speaks",
    category: "social",
    sample: "GUARANTEES",
    style: { ...DEFAULT_STYLE },
  },
  {
    id: "hero-pill",
    name: "Hero Pill",
    category: "social",
    sample: "Tanglish",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "Poppins",
      fontWeight: 700,
      fontSizePct: 3.6,
      color: "#A0A0A0",
      highlightColor: "#000000",
      outlineColor: "#FFFFFF",
      outlineWidth: 0,
      shadow: false,
      glowStrength: 0,
      backgroundColor: "#FFFFFF",
      backgroundOpacity: 1,
      bgPaddingXPct: 2.2,
      bgPaddingYPct: 1.1,
      boxMode: "pill",
      boxRadiusPct: 1.6,
      align: "center",
      positionYPct: 58,
      maxWidthPct: 88,
      letterSpacingEm: 0,
      lineHeight: 1,
      textCase: "sentence",
      uppercase: false,
      karaoke: true,
      emphasisMode: "off",
      animation: "fade",
      textEffect: "none",
    },
  },
  {
    id: "premium-1",
    name: "Premium Style 1",
    category: "social",
    sample: "podcast",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "Montserrat",
      fontWeight: 700,
      fontSizePct: 5.2,
      color: "#FFFFFF",
      highlightColor: "#FFFFFF",
      outlineColor: "#000000",
      outlineWidth: 0,
      shadow: true,
      glowStrength: 0,
      backgroundOpacity: 0,
      boxMode: "none",
      align: "center",
      positionYPct: 48,
      maxWidthPct: 92,
      letterSpacingEm: -0.02,
      lineHeight: 1,
      textCase: "lower",
      uppercase: false,
      karaoke: false,
      emphasisMode: "off",
      animation: "kinetic",
      textEffect: "none",
    },
  },
  {
    id: "premium-2",
    name: "Premium Style 2",
    category: "social",
    sample: "that every",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "Montserrat",
      fontWeight: 700,
      fontSizePct: 5.2,
      color: "#FFFFFF",
      highlightColor: "#FFFFFF",
      outlineColor: "#000000",
      outlineWidth: 0,
      shadow: true,
      glowStrength: 0,
      backgroundOpacity: 0,
      boxMode: "none",
      align: "center",
      positionYPct: 42,
      maxWidthPct: 94,
      letterSpacingEm: -0.02,
      lineHeight: 1,
      textCase: "lower",
      uppercase: false,
      karaoke: false,
      emphasisMode: "off",
      animation: "scatter",
      textEffect: "none",
    },
  },
  {
    id: "premium-3",
    name: "Premium Style 3",
    category: "social",
    sample: "ownership",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "Montserrat",
      fontWeight: 700,
      fontSizePct: 4.8,
      color: "#FFFFFF",
      highlightColor: "#FF4EC8",
      outlineColor: "#000000",
      outlineWidth: 0,
      shadow: false,
      glowStrength: 5,
      glowColor: "#FF4EC8",
      backgroundOpacity: 0,
      boxMode: "none",
      align: "center",
      positionYPct: 52,
      maxWidthPct: 90,
      letterSpacingEm: -0.01,
      lineHeight: 1.05,
      textCase: "sentence",
      uppercase: false,
      karaoke: false,
      emphasisMode: "off",
      animation: "hook",
      textEffect: "none",
    },
  },
  {
    id: "premium-4",
    name: "Premium Style 4",
    category: "social",
    sample: "BYPRODUCT",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "Montserrat",
      fontWeight: 700,
      fontSizePct: 5.8,
      color: "#FFFFFF",
      highlightColor: "#FFB020",
      outlineColor: "#000000",
      outlineWidth: 0,
      shadow: true,
      glowStrength: 0,
      backgroundOpacity: 0,
      boxMode: "none",
      align: "center",
      positionYPct: 58,
      maxWidthPct: 88,
      letterSpacingEm: -0.03,
      lineHeight: 1,
      textCase: "upper",
      uppercase: true,
      karaoke: false,
      emphasisMode: "auto",
      animation: "flash",
      textEffect: "none",
    },
  },
  {
    id: "premium-5",
    name: "Premium Style 5",
    category: "social",
    sample: "literally",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "Montserrat",
      fontWeight: 700,
      fontSizePct: 5.0,
      color: "#FFFFFF",
      highlightColor: "#2F8CFF",
      outlineColor: "#000000",
      outlineWidth: 0,
      shadow: true,
      glowStrength: 0,
      backgroundOpacity: 0,
      boxMode: "none",
      align: "center",
      positionYPct: 52,
      maxWidthPct: 88,
      letterSpacingEm: -0.02,
      lineHeight: 1.05,
      textCase: "lower",
      uppercase: false,
      karaoke: false,
      emphasisMode: "off",
      animation: "editorial",
      textEffect: "none",
    },
  },
  {
    id: "soft-whisper",
    name: "Soft Whisper",
    category: "social",
    sample: "quietly",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "Noto Sans Telugu",
      fontWeight: 500,
      fontSizePct: 3.2,
      color: "#FFFFFF",
      outlineWidth: 0,
      shadow: true,
      glowStrength: 0,
      positionYPct: 86,
      maxWidthPct: 88,
      letterSpacingEm: 0,
      lineHeight: 1.2,
      textCase: "sentence",
      emphasisMode: "off",
      animation: "fade",
      karaoke: false,
      boxMode: "none",
      backgroundOpacity: 0,
    },
  },
  {
    id: "clean",
    name: "Clean",
    category: "social",
    sample: "Namaskaram",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "Noto Sans Telugu",
      fontSizePct: 5.5,
      outlineWidth: 3,
      positionYPct: 86,
      maxWidthPct: 90,
      letterSpacingEm: 0,
      lineHeight: 1.25,
      animation: "none",
      emphasisMode: "off",
    },
  },
  {
    id: "bold-outline",
    name: "Bold Outline",
    category: "social",
    sample: "Bro listen",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "NTR",
      fontWeight: 700,
      fontSizePct: 6.5,
      color: "#FFFFFF",
      outlineColor: "#000000",
      outlineWidth: 5,
      shadow: true,
      animation: "pop",
    },
  },
  {
    id: "yellow-pop",
    name: "Yellow Pop",
    category: "social",
    sample: "Watch this",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "NTR",
      fontWeight: 700,
      fontSizePct: 6,
      color: "#FFE100",
      outlineColor: "#000000",
      outlineWidth: 4,
      animation: "pop",
    },
  },
  {
    id: "reels-punch",
    name: "Reels Punch",
    category: "social",
    sample: "Don't miss",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "NTR",
      fontWeight: 700,
      fontSizePct: 7,
      color: "#FFFFFF",
      outlineColor: "#FF0050",
      outlineWidth: 4,
      shadow: true,
      positionYPct: 78,
      uppercase: true,
      textCase: "upper",
      letterSpacingEm: 0.04,
      animation: "pop",
    },
  },
  // —— Cinematic ——
  {
    id: "prism-pro",
    name: "Prism Pro",
    category: "cinematic",
    sample: "First-Time",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "Noto Sans Telugu",
      fontWeight: 700,
      fontSizePct: 6.2,
      color: "#F5F8FF",
      outlineColor: "#C8D8F0",
      outlineWidth: 1.5,
      shadow: true,
      positionYPct: 28,
      letterSpacingEm: 0.01,
      maxWidthPct: 88,
      lineHeight: 1.15,
      animation: "fade",
      textEffect: "prism",
      glowStrength: 0,
      boxMode: "none",
      backgroundOpacity: 0,
      karaoke: false,
    },
  },
  {
    id: "cinematic",
    name: "Cinematic",
    category: "cinematic",
    sample: "Once upon",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "Suranna",
      fontWeight: 400,
      fontSizePct: 5,
      color: "#F5E6C8",
      outlineColor: "#000000",
      outlineWidth: 2,
      shadow: true,
      positionYPct: 90,
      letterSpacingEm: 0.02,
      animation: "fade",
    },
  },
  {
    id: "film-serif",
    name: "Film Serif",
    category: "cinematic",
    sample: "Chapter one",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "Ramaraja",
      fontWeight: 400,
      fontSizePct: 5.2,
      color: "#FFE8C8",
      outlineColor: "#1A1208",
      outlineWidth: 2.5,
      shadow: true,
      letterSpacingEm: 0.03,
      positionYPct: 88,
      animation: "fade",
    },
  },
  {
    id: "soft-cream",
    name: "Soft Cream",
    category: "cinematic",
    sample: "Quiet night",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "Suranna",
      fontWeight: 400,
      fontSizePct: 4.8,
      color: "#FFF5E0",
      outlineWidth: 0,
      shadow: true,
      backgroundColor: "#2A2118",
      backgroundOpacity: 0.55,
      bgPaddingXPct: 2,
      bgPaddingYPct: 0.9,
      boxMode: "pill",
      boxRadiusPct: 1.5,
      positionYPct: 86,
      animation: "fade",
    },
  },
  {
    id: "dark-moody",
    name: "Dark Moody",
    category: "cinematic",
    sample: "Midnight",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "Dhurjati",
      fontWeight: 400,
      fontSizePct: 5.5,
      color: "#E8E0F0",
      outlineColor: "#0A0612",
      outlineWidth: 2,
      shadow: true,
      glowStrength: 2,
      glowColor: "#A78BFA",
      positionYPct: 84,
      animation: "fade",
    },
  },

  // —— Karaoke ——
  {
    id: "karaoke",
    name: "Karaoke Classic",
    category: "karaoke",
    sample: "Sing along",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "NTR",
      fontWeight: 700,
      fontSizePct: 6.5,
      color: "#FFFFFF",
      outlineColor: "#000000",
      outlineWidth: 4,
      shadow: true,
      positionYPct: 82,
      karaoke: true,
      highlightColor: "#FFE100",
    },
  },
  {
    id: "karaoke-pink",
    name: "Pink Beat",
    category: "karaoke",
    sample: "Feel the beat",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "NTR",
      fontWeight: 700,
      fontSizePct: 6.5,
      color: "#FFFFFF",
      outlineColor: "#2D0A1A",
      outlineWidth: 3.5,
      shadow: true,
      karaoke: true,
      highlightColor: "#FF4DB8",
      glowStrength: 2,
      glowColor: "#FF4DB8",
      positionYPct: 80,
      animation: "fade",
    },
  },
  {
    id: "karaoke-green",
    name: "Green Spot",
    category: "karaoke",
    sample: "Next line",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "Gidugu",
      fontWeight: 700,
      fontSizePct: 6.2,
      color: "#E8FFE8",
      outlineColor: "#001A00",
      outlineWidth: 3.5,
      shadow: true,
      karaoke: true,
      highlightColor: "#39FF14",
      glowStrength: 3,
      glowColor: "#39FF14",
      positionYPct: 82,
    },
  },

  // —— Minimal ——
  {
    id: "minimal",
    name: "Minimal",
    category: "minimal",
    sample: "Keep it simple",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "Noto Sans Telugu",
      fontWeight: 400,
      fontSizePct: 4.5,
      outlineWidth: 0,
      shadow: true,
    },
  },
  {
    id: "whisper-white",
    name: "Whisper White",
    category: "minimal",
    sample: "Soft words",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "Mallanna",
      fontWeight: 400,
      fontSizePct: 4.2,
      color: "#F8FAFC",
      outlineWidth: 0,
      shadow: true,
      letterSpacingEm: 0.02,
      positionYPct: 88,
      animation: "fade",
    },
  },
  {
    id: "soft-box-podcast",
    name: "Podcast Soft",
    category: "minimal",
    sample: "Episode 12",
    style: {
      ...DEFAULT_STYLE,
      fontFamily: "Noto Sans Telugu",
      fontWeight: 500,
      fontSizePct: 4.8,
      color: "#F1F5F9",
      outlineWidth: 0,
      shadow: false,
      backgroundColor: "#0F172A",
      backgroundOpacity: 0.7,
      bgPaddingXPct: 2.4,
      bgPaddingYPct: 1.1,
      boxMode: "pill",
      boxRadiusPct: 2,
      positionYPct: 90,
      maxWidthPct: 85,
      animation: "fade",
    },
  },
];

/** Find the preset whose style matches `style` field-for-field (used to highlight the card). */
export function matchingPresetId(style: SubtitleStyle): string | null {
  for (const p of PRESETS) {
    if (stylesEqual(p.style, style)) return p.id;
  }
  return null;
}

function stylesEqual(a: SubtitleStyle, b: SubtitleStyle): boolean {
  const keys = Object.keys(DEFAULT_STYLE) as (keyof SubtitleStyle)[];
  return keys.every((k) => a[k] === b[k]);
}
